import { ArrowUpRight, Flame, Snowflake, Waves, Wind } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { AppHeader } from '../components/AppHeader'
import { CategoryCard } from '../components/explore/CategoryCard'
import { RegionCard } from '../components/explore/RegionCard'
import { WeatherSpotlight } from '../components/explore/WeatherSpotlight'
import { GlassCard } from '../components/ui/GlassCard'
import { useWeather } from '../context/WeatherContext'
import { getCondition } from '../utils/weather'

const categories = [{ title: 'Sunny Destinations', icon: 'sun', description: 'Find places with sunshine year-round', city: 'Dubai' }, { title: 'Rainy Places', icon: 'rain', description: 'Explore places with the most rainfall', city: 'Mumbai' }, { title: 'Snowy Locations', icon: 'snow', description: 'Discover places that are cold and snowy', city: 'Toronto' }, { title: 'Windy Cities', icon: 'wind', description: 'Explore breezy coastal weather', city: 'Sydney' }, { title: 'Sunrise & Sunset', icon: 'sunrise', description: 'Witness beautiful golden-hour skies', city: 'Paris' }]
const regions = [{ title: 'Asia', detail: 'Asian countries', city: 'Hyderabad' }, { title: 'Europe', detail: 'European countries', city: 'London' }, { title: 'North America', detail: 'North American cities', city: 'New York' }, { title: 'South America', detail: 'South American cities', city: 'São Paulo' }, { title: 'Africa', detail: 'African countries', city: 'Cape Town' }, { title: 'Oceania', detail: 'Oceanian cities', city: 'Sydney' }]

export function ExplorePage() {
  const { weather, searchAndSelect } = useWeather()
  const navigate = useNavigate()
  const condition = getCondition(weather?.current?.weatherCode)
  const exploreCity = async (city) => { try { const selected = await searchAndSelect(city); navigate(`/weather/${encodeURIComponent(selected.name)}`) } catch { /* the global banner keeps the current cached view usable */ } }
  const insights = [{ title: 'Heatwave alert', description: 'Check high temperatures and hydration needs before midday.', value: weather?.current?.temperature >= 34 ? 'High' : 'Watch', icon: Flame, tone: 'orange' }, { title: 'Rainfall outlook', description: 'The next hours may bring changing cloud and rain conditions.', value: `${weather?.current?.rain ?? 0} mm`, icon: Waves, tone: 'blue' }, { title: 'Wind watch', description: 'Plan open-air activities around local wind speeds.', value: `${Math.round(weather?.current?.windSpeed ?? 0)} km/h`, icon: Wind, tone: 'teal' }, { title: 'Cold front', description: 'Cooler locations are featured across the regions list.', value: condition.condition === 'snow' ? 'Active' : 'Quiet', icon: Snowflake, tone: 'violet' }]
  return <div className="page-container"><AppHeader title="Explore the Weather" subtitle="Discover weather around the world" /><div className="page-content explore-content"><section><div className="section-heading-row"><div><p className="eyebrow">Discover by mood</p><h2>Explore by Category</h2></div></div><div className="category-grid">{categories.map((category) => <CategoryCard key={category.title} category={category} onClick={() => exploreCity(category.city)} />)}</div></section><section><div className="section-heading-row"><div><p className="eyebrow">Forecasts everywhere</p><h2>Explore by Region</h2></div></div><div className="region-grid">{regions.map((region) => <RegionCard key={region.title} region={region} onClick={() => exploreCity(region.city)} />)}</div></section><div className="explore-bottom-grid"><section><div className="section-heading-row"><div><p className="eyebrow">Live signals</p><h2>Trending Weather Insights</h2></div><button className="text-button" type="button">View all <ArrowUpRight size={15} /></button></div><GlassCard className="insights-card">{insights.map(({ title, description, value, icon: Icon, tone }) => <button className="insight-row" key={title} type="button" onClick={() => exploreCity(weather?.city?.name ?? 'Hyderabad')}><span className={`insight-icon insight-${tone}`}><Icon size={19} /></span><span><strong>{title}</strong><small>{description}</small></span><b>{value}</b><ArrowUpRight size={16} /></button>)}</GlassCard></section><section><div className="section-heading-row"><div><p className="eyebrow">Featured event</p><h2>Weather Spotlight</h2></div><span className="muted-text">Live now</span></div><WeatherSpotlight /></section></div></div></div>
}
